// TOEFL Reading "Complete the Words" 연습용 학술 문단
// 각 문단은 약 50~80단어, 2~3문장으로 구성
// 주제별로 분류하여 관리

export interface Passage {
  id: number;
  topic: string; // 주제 분류
  text: string; // 지문 본문
  translation: string; // 지문 한국어 번역
}

export const samplePassages: Passage[] = [
  // ─── 생물학 (Biology) ───
  {
    id: 1,
    topic: "Biology",
    text: `The process of photosynthesis is fundamental to life on Earth. Plants absorb sunlight through specialized structures called chloroplasts and convert carbon dioxide into organic compounds that serve as energy sources for nearly all living organisms in the biosphere.`,
    translation: `광합성(photosynthesis)은 지구 생명의 근간이 되는 과정이다. 식물은 엽록체(chloroplast)라는 특수한 구조를 통해 햇빛을 흡수하고, 이산화탄소를 생물권의 거의 모든 생물에게 에너지원이 되는 유기 화합물로 전환한다.`,
  },
  {
    id: 2,
    topic: "Biology",
    text: `The development of antibiotics transformed medical practice in the twentieth century. Researchers discovered that certain naturally occurring compounds produced by microorganisms could effectively eliminate harmful bacterial infections that had previously caused widespread mortality throughout human populations.`,
    translation: `항생제(antibiotics)의 개발은 20세기 의료 관행을 근본적으로 변화시켰다. 연구자들은 미생물이 생성하는 특정 천연 화합물이 이전에 인류 전체에 걸쳐 광범위한 사망을 초래했던 유해한 세균 감염을 효과적으로 제거할 수 있다는 사실을 발견했다.`,
  },
  {
    id: 3,
    topic: "Biology",
    text: `Coral reef ecosystems support an extraordinary diversity of marine life despite occupying relatively small areas of the ocean floor. Biologists estimate that approximately one quarter of all identified marine species depend on healthy reef structures for essential activities including feeding and reproduction.`,
    translation: `산호초 생태계는 해저의 비교적 작은 면적을 차지함에도 불구하고 놀라울 정도로 다양한 해양 생물을 부양한다. 생물학자들은 확인된 전체 해양 종의 약 4분의 1이 먹이 활동과 번식을 포함한 필수적인 활동을 위해 건강한 산호초 구조에 의존한다고 추정한다.`,
  },
  {
    id: 4,
    topic: "Biology",
    text: `Migration patterns in birds are governed by a complex interaction of genetic programming and environmental cues. Scientists have determined that many species navigate using the position of the sun and stars combined with sensitivity to magnetic fields generated by the planet's iron core.`,
    translation: `새의 이동(migration) 패턴은 유전적 프로그래밍과 환경적 신호의 복잡한 상호작용에 의해 결정된다. 과학자들은 많은 종이 태양과 별의 위치를 활용하고, 지구의 철 핵이 생성하는 자기장에 대한 감지 능력을 결합하여 길을 찾는다는 사실을 밝혀냈다.`,
  },
  {
    id: 5,
    topic: "Biology",
    text: `The human immune system employs multiple layers of defense against invading pathogens. White blood cells circulate throughout the body and identify foreign substances by recognizing specific molecular patterns that distinguish harmful organisms from the body's own healthy tissues.`,
    translation: `인체 면역 체계는 침입하는 병원체(pathogen)에 대해 여러 겹의 방어 체계를 사용한다. 백혈구는 몸 전체를 순환하며 유해 생물을 신체 자체의 건강한 조직과 구별하는 특정 분자 패턴을 인식함으로써 외부 물질을 식별한다.`,
  },
  {
    id: 6,
    topic: "Biology",
    text: `Rainforest canopies create distinct microclimates that support unique communities of organisms at different vertical levels. Researchers have found that temperature and humidity conditions vary significantly between the forest floor and the uppermost branches where direct sunlight penetrates the dense vegetation.`,
    translation: `열대우림의 캐노피(canopy, 수관층)는 수직 높이에 따라 고유한 생물 군집을 지탱하는 독특한 미기후를 형성한다. 연구자들은 숲 바닥과 직사광선이 빽빽한 식생을 뚫고 들어오는 최상층 가지 사이에서 온도와 습도 조건이 크게 다르다는 것을 발견했다.`,
  },
  {
    id: 7,
    topic: "Biology",
    text: `Enzymes are biological catalysts that accelerate chemical reactions within living cells without being consumed in the process. Each enzyme has a uniquely shaped active site that binds only to specific substrate molecules and facilitates their transformation into different chemical products.`,
    translation: `효소(enzyme)는 살아있는 세포 내에서 화학 반응을 촉진하면서도 그 과정에서 소모되지 않는 생물학적 촉매이다. 각 효소는 특정 기질(substrate) 분자에만 결합하는 고유한 형태의 활성 부위를 가지고 있으며, 이를 다른 화학 생성물로 전환하는 것을 촉진한다.`,
  },

  // ─── 지구과학 (Earth Science) ───
  {
    id: 8,
    topic: "Earth Science",
    text: `The theory of plate tectonics revolutionized our understanding of geological processes. Scientists observed that continental landmasses gradually shift their positions over millions of years through movement along boundaries where massive plates of rock interact beneath the surface.`,
    translation: `판구조론(plate tectonics)은 지질학적 과정에 대한 우리의 이해를 혁명적으로 바꾸었다. 과학자들은 대륙이 수백만 년에 걸쳐 지표면 아래에서 거대한 암석판들이 상호작용하는 경계를 따라 이동하면서 점진적으로 위치를 바꾼다는 사실을 관찰했다.`,
  },
  {
    id: 9,
    topic: "Earth Science",
    text: `Climate change represents one of the most significant challenges facing modern society. Studies indicate that rising global temperatures have accelerated the melting of polar ice formations and contributed to measurable increases in average sea levels across multiple coastal regions worldwide.`,
    translation: `기후 변화(climate change)는 현대 사회가 직면한 가장 중대한 과제 중 하나이다. 연구에 따르면 지구 기온 상승이 극지방 빙하의 융해를 가속화하고, 전 세계 여러 해안 지역에서 평균 해수면의 측정 가능한 상승에 기여하고 있다.`,
  },
  {
    id: 10,
    topic: "Earth Science",
    text: `Volcanic eruptions release enormous quantities of gases and particulate matter into the atmosphere. Major eruptions have historically caused temporary global cooling by injecting sulfur dioxide particles into the stratosphere where they reflect incoming solar radiation back into space.`,
    translation: `화산 폭발은 막대한 양의 가스와 미립자 물질을 대기 중으로 방출한다. 역사적으로 대규모 화산 폭발은 이산화황(sulfur dioxide) 입자를 성층권에 주입하여 유입되는 태양 복사를 우주로 반사시킴으로써 일시적인 지구 냉각을 초래했다.`,
  },
  {
    id: 11,
    topic: "Earth Science",
    text: `Ocean currents play a critical role in regulating global climate patterns and distributing thermal energy. The Gulf Stream transports warm tropical water northward along the Atlantic coast and moderates winter temperatures across northwestern European countries that would otherwise experience significantly colder conditions.`,
    translation: `해류(ocean current)는 전 지구적 기후 패턴을 조절하고 열에너지를 분배하는 데 핵심적인 역할을 한다. 멕시코 만류(Gulf Stream)는 따뜻한 열대 해수를 대서양 연안을 따라 북쪽으로 운반하며, 그렇지 않으면 훨씬 추운 기후를 경험했을 북서유럽 국가들의 겨울 기온을 완화시킨다.`,
  },
  {
    id: 12,
    topic: "Earth Science",
    text: `Earthquakes occur when accumulated stress along geological fault lines exceeds the strength of surrounding rock formations. Seismologists use sensitive instruments called seismographs to detect and measure ground vibrations that travel outward from the rupture point in patterns of primary and secondary waves.`,
    translation: `지진은 지질학적 단층선을 따라 축적된 응력이 주변 암석의 강도를 초과할 때 발생한다. 지진학자들은 지진계(seismograph)라는 정밀 기기를 사용하여 파열 지점에서 1차파(P파)와 2차파(S파) 형태로 외부로 전파되는 지반 진동을 감지하고 측정한다.`,
  },
  {
    id: 13,
    topic: "Earth Science",
    text: `Glaciers have shaped much of the modern landscape through slow but powerful erosional processes over thousands of years. These massive bodies of compressed ice carved deep valleys and deposited enormous quantities of sediment that formed distinctive geological features still visible across northern continents today.`,
    translation: `빙하(glacier)는 수천 년에 걸친 느리지만 강력한 침식 과정을 통해 현대 지형의 상당 부분을 형성했다. 이 거대한 압축 얼음 덩어리들은 깊은 계곡을 깎아내고 막대한 양의 퇴적물을 쌓아 올려, 오늘날까지 북부 대륙 곳곳에서 볼 수 있는 독특한 지질학적 지형을 만들었다.`,
  },

  // ─── 역사 (History) ───
  {
    id: 14,
    topic: "History",
    text: `Archaeological evidence suggests that early human civilizations developed agriculture independently in several regions around the world. Researchers have discovered ancient farming tools and cultivated grain remnants that indicate sophisticated knowledge of seasonal patterns and soil management techniques.`,
    translation: `고고학적 증거에 따르면 초기 인류 문명은 세계 여러 지역에서 독립적으로 농업을 발전시켰다. 연구자들은 계절 패턴과 토양 관리 기술에 대한 정교한 지식을 보여주는 고대 농기구와 재배된 곡물 잔해를 발견했다.`,
  },
  {
    id: 15,
    topic: "History",
    text: `The invention of the printing press dramatically accelerated the spread of knowledge across European societies. Scholars gained unprecedented access to philosophical texts and scientific manuscripts that had previously been available only through expensive hand-copied reproductions in monastic libraries.`,
    translation: `인쇄기(printing press)의 발명은 유럽 사회 전반에 걸친 지식의 전파를 극적으로 가속화했다. 학자들은 이전에 수도원 도서관의 값비싼 필사본으로만 접할 수 있었던 철학 서적과 과학 원고에 전례 없는 접근이 가능해졌다.`,
  },
  {
    id: 16,
    topic: "History",
    text: `The Industrial Revolution fundamentally altered economic structures and social relationships throughout Western nations. Factory production replaced traditional craft workshops and created massive urban centers where workers concentrated in dense residential districts surrounding large manufacturing facilities.`,
    translation: `산업혁명(Industrial Revolution)은 서방 국가 전역의 경제 구조와 사회적 관계를 근본적으로 변화시켰다. 공장 생산이 전통적인 수공업 작업장을 대체했으며, 대규모 제조 시설 주변의 밀집된 주거 지역에 노동자들이 집중하는 거대한 도시 중심지가 형성되었다.`,
  },
  {
    id: 17,
    topic: "History",
    text: `Ancient Egyptian civilization flourished along the fertile banks of the Nile River for over three thousand years. Engineers constructed elaborate irrigation systems that channeled seasonal floodwaters into agricultural fields and enabled consistent crop production in an otherwise arid desert environment.`,
    translation: `고대 이집트 문명은 나일강의 비옥한 유역을 따라 3천 년 이상 번성했다. 기술자들은 계절적 홍수를 농경지로 끌어들이는 정교한 관개 시스템을 건설하여, 원래라면 메마른 사막 환경에서도 안정적인 작물 생산이 가능하도록 했다.`,
  },
  {
    id: 18,
    topic: "History",
    text: `The Silk Road connected distant civilizations across Asia and Europe through an extensive network of trading routes. Merchants transported luxury goods including silk and spices while simultaneously facilitating the exchange of religious ideas and technological innovations between culturally diverse societies.`,
    translation: `실크로드(Silk Road)는 광범위한 무역로 네트워크를 통해 아시아와 유럽의 먼 문명들을 연결했다. 상인들은 비단과 향신료를 포함한 사치품을 운송하는 동시에, 문화적으로 다양한 사회들 사이에서 종교적 사상과 기술 혁신의 교류를 촉진했다.`,
  },
  {
    id: 19,
    topic: "History",
    text: `The Renaissance marked a profound cultural transformation in European intellectual and artistic traditions. Scholars rediscovered classical Greek and Roman philosophical works that inspired new approaches to understanding human nature and challenged established religious interpretations of the natural world.`,
    translation: `르네상스(Renaissance)는 유럽의 지적, 예술적 전통에 있어 심대한 문화적 변혁을 의미했다. 학자들은 고대 그리스와 로마의 철학 저작을 재발견하여 인간 본성을 이해하는 새로운 접근법에 영감을 주었고, 자연 세계에 대한 기존의 종교적 해석에 도전했다.`,
  },

  // ─── 심리학 / 신경과학 (Psychology / Neuroscience) ───
  {
    id: 20,
    topic: "Psychology",
    text: `Neuroscience research has revealed remarkable plasticity in the adult human brain. Experiments demonstrate that neural pathways can reorganize themselves throughout an individual's lifetime in response to learning experiences and environmental stimulation that challenge existing cognitive patterns.`,
    translation: `신경과학(neuroscience) 연구는 성인 인간의 뇌에서 놀라운 가소성(plasticity)을 밝혀냈다. 실험에 따르면 신경 경로는 기존의 인지 패턴에 도전하는 학습 경험과 환경적 자극에 반응하여 개인의 생애 전반에 걸쳐 스스로 재조직될 수 있다.`,
  },
  {
    id: 21,
    topic: "Psychology",
    text: `Memory consolidation occurs primarily during specific stages of sleep when the brain processes and organizes information gathered throughout the day. Studies show that individuals who receive adequate rest perform significantly better on tasks requiring recall of recently learned material and complex problem solving.`,
    translation: `기억 공고화(memory consolidation)는 뇌가 하루 동안 수집한 정보를 처리하고 정리하는 수면의 특정 단계에서 주로 발생한다. 연구에 따르면 충분한 휴식을 취한 사람들은 최근 학습한 내용의 회상과 복잡한 문제 해결을 요하는 과제에서 현저히 더 나은 수행을 보인다.`,
  },
  {
    id: 22,
    topic: "Psychology",
    text: `Language acquisition in children follows remarkably consistent developmental stages regardless of cultural background. Linguists have observed that infants begin by producing universal babbling sounds before gradually narrowing their vocal repertoire to match the specific phonetic patterns heard in their surrounding environment.`,
    translation: `아동의 언어 습득(language acquisition)은 문화적 배경에 관계없이 놀라울 정도로 일관된 발달 단계를 따른다. 언어학자들은 영아가 처음에 보편적인 옹알이 소리를 내다가, 점차 주변 환경에서 듣는 특정 음성 패턴에 맞추어 음성 목록을 좁혀간다는 것을 관찰했다.`,
  },
  {
    id: 23,
    topic: "Psychology",
    text: `Social conformity experiments have demonstrated powerful influences on individual decision making within group settings. Participants frequently abandoned their own accurate judgments and adopted clearly incorrect answers when confronted with unanimous opposing opinions expressed by other members of the experimental group.`,
    translation: `사회적 동조(social conformity) 실험은 집단 환경에서 개인의 의사 결정에 미치는 강력한 영향을 입증했다. 참가자들은 실험 집단의 다른 구성원들이 표현한 만장일치의 반대 의견에 직면했을 때, 자신의 정확한 판단을 빈번히 포기하고 명백히 틀린 답을 채택했다.`,
  },

  // ─── 천문학 / 물리학 (Astronomy / Physics) ───
  {
    id: 24,
    topic: "Astronomy",
    text: `The expanding universe theory fundamentally changed our understanding of cosmic origins and development. Astronomers discovered that distant galaxies are moving away from each other at accelerating velocities which suggests that all matter originated from an incredibly dense singular point approximately fourteen billion years ago.`,
    translation: `팽창 우주론(expanding universe theory)은 우주의 기원과 발전에 대한 우리의 이해를 근본적으로 바꾸었다. 천문학자들은 먼 은하들이 가속하는 속도로 서로 멀어지고 있다는 사실을 발견했으며, 이는 약 140억 년 전 모든 물질이 믿을 수 없이 밀도가 높은 하나의 점에서 기원했음을 시사한다.`,
  },
  {
    id: 25,
    topic: "Astronomy",
    text: `Black holes represent some of the most extreme objects predicted by general relativity theory. These regions of spacetime exhibit gravitational forces so powerful that nothing including electromagnetic radiation can escape once it crosses the boundary known as the event horizon surrounding the collapsed stellar core.`,
    translation: `블랙홀(black hole)은 일반 상대성 이론이 예측한 가장 극단적인 천체 중 하나이다. 이 시공간 영역은 너무나 강력한 중력을 나타내어, 전자기 복사를 포함한 그 어떤 것도 붕괴된 항성 핵을 둘러싼 사건의 지평선(event horizon)이라 불리는 경계를 넘으면 탈출할 수 없다.`,
  },
  {
    id: 26,
    topic: "Astronomy",
    text: `Mars has attracted significant scientific attention as a potential candidate for future human exploration and settlement. Robotic missions have confirmed the presence of frozen water deposits beneath the planetary surface and identified mineral compositions that suggest liquid water once flowed across extensive Martian landscapes.`,
    translation: `화성(Mars)은 미래 인류 탐사와 정착의 잠재적 후보지로서 상당한 과학적 관심을 끌어왔다. 로봇 탐사 임무를 통해 행성 표면 아래 얼음 상태의 물 퇴적물이 존재함을 확인했으며, 과거에 광활한 화성 지표 위로 액체 상태의 물이 흘렀음을 시사하는 광물 조성을 확인했다.`,
  },

  // ─── 환경과학 (Environmental Science) ───
  {
    id: 27,
    topic: "Environmental Science",
    text: `Deforestation in tropical regions contributes significantly to biodiversity loss and atmospheric carbon accumulation. Conservation organizations advocate for sustainable forestry practices that balance economic development needs with preservation of critical habitat areas that support endangered plant and animal species.`,
    translation: `열대 지역의 삼림 벌채(deforestation)는 생물 다양성 손실과 대기 중 탄소 축적에 크게 기여한다. 보존 단체들은 경제 개발의 필요와 멸종 위기 동식물 종을 지탱하는 핵심 서식지 보존의 균형을 맞추는 지속 가능한 산림 관행을 옹호하고 있다.`,
  },
  {
    id: 28,
    topic: "Environmental Science",
    text: `Plastic pollution has emerged as a major environmental concern affecting marine ecosystems worldwide. Researchers have documented microscopic plastic fragments in ocean water samples collected from every major body of water and detected these persistent synthetic materials throughout aquatic food chains.`,
    translation: `플라스틱 오염은 전 세계 해양 생태계에 영향을 미치는 주요 환경 문제로 대두되었다. 연구자들은 모든 주요 수역에서 채취한 해양 수질 시료에서 미세 플라스틱(microplastic) 조각을 기록했으며, 수중 먹이 사슬 전반에서 이 잔류성 합성 물질을 검출했다.`,
  },
  {
    id: 29,
    topic: "Environmental Science",
    text: `Renewable energy technologies have advanced rapidly as alternatives to traditional fossil fuel consumption. Solar panel efficiency has improved dramatically while manufacturing costs have decreased substantially making photovoltaic systems increasingly competitive with conventional electricity generation methods in numerous global markets.`,
    translation: `재생 에너지(renewable energy) 기술은 기존 화석 연료 소비의 대안으로서 빠르게 발전해왔다. 태양광 패널의 효율이 극적으로 향상되는 동시에 제조 비용이 대폭 감소하여, 태양광 발전(photovoltaic) 시스템이 수많은 글로벌 시장에서 기존 전력 생산 방식과 점점 더 경쟁력을 갖추고 있다.`,
  },

  // ─── 사회학 / 경제학 (Sociology / Economics) ───
  {
    id: 30,
    topic: "Sociology",
    text: `Urbanization has transformed demographic patterns across developing nations throughout recent decades. Rural populations have migrated toward metropolitan centers in search of improved employment opportunities and access to educational institutions that provide pathways to higher economic mobility and professional advancement.`,
    translation: `도시화(urbanization)는 최근 수십 년에 걸쳐 개발도상국 전역의 인구 통계 패턴을 변화시켰다. 농촌 인구는 더 나은 취업 기회와 경제적 이동성 및 직업적 발전의 경로를 제공하는 교육 기관에 대한 접근을 찾아 대도시 중심지로 이주해왔다.`,
  },
  {
    id: 31,
    topic: "Economics",
    text: `International trade agreements have reshaped global economic relationships between developing and industrialized nations. Economists debate whether reduced tariff barriers genuinely promote equitable growth or primarily advantage established corporations that possess sufficient resources to exploit expanded market access opportunities.`,
    translation: `국제 무역 협정은 개발도상국과 선진국 간의 글로벌 경제 관계를 재편했다. 경제학자들은 관세 장벽의 인하가 진정으로 공평한 성장을 촉진하는지, 아니면 확대된 시장 접근 기회를 활용할 충분한 자원을 보유한 기존 기업들에게 주로 유리한지를 두고 논쟁하고 있다.`,
  },
  {
    id: 32,
    topic: "Sociology",
    text: `Digital communication technologies have fundamentally altered patterns of social interaction among younger generations. Researchers observe that online platforms increasingly serve as primary spaces for community formation and identity development replacing traditional physical gathering locations that previously fulfilled these essential social functions.`,
    translation: `디지털 커뮤니케이션 기술은 젊은 세대의 사회적 상호작용 패턴을 근본적으로 변화시켰다. 연구자들은 온라인 플랫폼이 이전에 이러한 필수적인 사회적 기능을 수행했던 전통적인 물리적 모임 장소를 대체하며, 점점 더 커뮤니티 형성과 정체성 발달의 주요 공간 역할을 하고 있다고 관찰한다.`,
  },

  // ─── 기술 (Technology) ───
  {
    id: 33,
    topic: "Technology",
    text: `Artificial intelligence systems have demonstrated remarkable capabilities in pattern recognition and data analysis tasks. Machine learning algorithms process enormous datasets and identify subtle correlations that human analysts might overlook enabling more accurate predictions in fields ranging from medical diagnosis to financial market forecasting.`,
    translation: `인공지능(AI) 시스템은 패턴 인식과 데이터 분석 과제에서 놀라운 능력을 입증해왔다. 머신러닝(machine learning) 알고리즘은 방대한 데이터셋을 처리하고 인간 분석가가 간과할 수 있는 미묘한 상관관계를 식별하여, 의료 진단에서 금융 시장 예측에 이르는 분야에서 더 정확한 예측을 가능하게 한다.`,
  },
  {
    id: 34,
    topic: "Technology",
    text: `The development of semiconductor technology enabled the miniaturization of electronic computing devices over several decades. Engineers consistently doubled the number of transistors on integrated circuits approximately every two years following a trend that dramatically increased processing power while reducing manufacturing costs.`,
    translation: `반도체(semiconductor) 기술의 발전은 수십 년에 걸쳐 전자 컴퓨팅 장치의 소형화를 가능하게 했다. 엔지니어들은 약 2년마다 집적 회로(integrated circuit)의 트랜지스터 수를 꾸준히 두 배로 늘리는 추세를 따랐으며, 이로써 제조 비용을 절감하면서도 처리 능력을 극적으로 향상시켰다.`,
  },
  {
    id: 35,
    topic: "Technology",
    text: `Quantum computing represents a fundamentally different approach to information processing compared with classical digital systems. These experimental machines exploit quantum mechanical phenomena including superposition and entanglement to perform certain categories of complex calculations exponentially faster than any conventional computer architecture.`,
    translation: `양자 컴퓨팅(quantum computing)은 고전적 디지털 시스템과 비교하여 정보 처리에 대한 근본적으로 다른 접근 방식을 나타낸다. 이 실험적 기계들은 중첩(superposition)과 얽힘(entanglement)을 포함한 양자역학적 현상을 활용하여, 특정 범주의 복잡한 계산을 기존의 어떤 컴퓨터 아키텍처보다 기하급수적으로 빠르게 수행한다.`,
  },
];
