// TOEFL Reading "Complete the Words" 연습용 학술 문단
// 각 문단은 약 50~80단어, 2~3문장으로 구성
// 주제별로 분류하여 관리

export interface Passage {
  id: number;
  topic: string; // 주제 분류
  text: string; // 지문 본문
}

export const samplePassages: Passage[] = [
  // ─── 생물학 (Biology) ───
  {
    id: 1,
    topic: "Biology",
    text: `The process of photosynthesis is fundamental to life on Earth. Plants absorb sunlight through specialized structures called chloroplasts and convert carbon dioxide into organic compounds that serve as energy sources for nearly all living organisms in the biosphere.`,
  },
  {
    id: 2,
    topic: "Biology",
    text: `The development of antibiotics transformed medical practice in the twentieth century. Researchers discovered that certain naturally occurring compounds produced by microorganisms could effectively eliminate harmful bacterial infections that had previously caused widespread mortality throughout human populations.`,
  },
  {
    id: 3,
    topic: "Biology",
    text: `Coral reef ecosystems support an extraordinary diversity of marine life despite occupying relatively small areas of the ocean floor. Biologists estimate that approximately one quarter of all identified marine species depend on healthy reef structures for essential activities including feeding and reproduction.`,
  },
  {
    id: 4,
    topic: "Biology",
    text: `Migration patterns in birds are governed by a complex interaction of genetic programming and environmental cues. Scientists have determined that many species navigate using the position of the sun and stars combined with sensitivity to magnetic fields generated by the planet's iron core.`,
  },
  {
    id: 5,
    topic: "Biology",
    text: `The human immune system employs multiple layers of defense against invading pathogens. White blood cells circulate throughout the body and identify foreign substances by recognizing specific molecular patterns that distinguish harmful organisms from the body's own healthy tissues.`,
  },
  {
    id: 6,
    topic: "Biology",
    text: `Rainforest canopies create distinct microclimates that support unique communities of organisms at different vertical levels. Researchers have found that temperature and humidity conditions vary significantly between the forest floor and the uppermost branches where direct sunlight penetrates the dense vegetation.`,
  },
  {
    id: 7,
    topic: "Biology",
    text: `Enzymes are biological catalysts that accelerate chemical reactions within living cells without being consumed in the process. Each enzyme has a uniquely shaped active site that binds only to specific substrate molecules and facilitates their transformation into different chemical products.`,
  },

  // ─── 지구과학 (Earth Science) ───
  {
    id: 8,
    topic: "Earth Science",
    text: `The theory of plate tectonics revolutionized our understanding of geological processes. Scientists observed that continental landmasses gradually shift their positions over millions of years through movement along boundaries where massive plates of rock interact beneath the surface.`,
  },
  {
    id: 9,
    topic: "Earth Science",
    text: `Climate change represents one of the most significant challenges facing modern society. Studies indicate that rising global temperatures have accelerated the melting of polar ice formations and contributed to measurable increases in average sea levels across multiple coastal regions worldwide.`,
  },
  {
    id: 10,
    topic: "Earth Science",
    text: `Volcanic eruptions release enormous quantities of gases and particulate matter into the atmosphere. Major eruptions have historically caused temporary global cooling by injecting sulfur dioxide particles into the stratosphere where they reflect incoming solar radiation back into space.`,
  },
  {
    id: 11,
    topic: "Earth Science",
    text: `Ocean currents play a critical role in regulating global climate patterns and distributing thermal energy. The Gulf Stream transports warm tropical water northward along the Atlantic coast and moderates winter temperatures across northwestern European countries that would otherwise experience significantly colder conditions.`,
  },
  {
    id: 12,
    topic: "Earth Science",
    text: `Earthquakes occur when accumulated stress along geological fault lines exceeds the strength of surrounding rock formations. Seismologists use sensitive instruments called seismographs to detect and measure ground vibrations that travel outward from the rupture point in patterns of primary and secondary waves.`,
  },
  {
    id: 13,
    topic: "Earth Science",
    text: `Glaciers have shaped much of the modern landscape through slow but powerful erosional processes over thousands of years. These massive bodies of compressed ice carved deep valleys and deposited enormous quantities of sediment that formed distinctive geological features still visible across northern continents today.`,
  },

  // ─── 역사 (History) ───
  {
    id: 14,
    topic: "History",
    text: `Archaeological evidence suggests that early human civilizations developed agriculture independently in several regions around the world. Researchers have discovered ancient farming tools and cultivated grain remnants that indicate sophisticated knowledge of seasonal patterns and soil management techniques.`,
  },
  {
    id: 15,
    topic: "History",
    text: `The invention of the printing press dramatically accelerated the spread of knowledge across European societies. Scholars gained unprecedented access to philosophical texts and scientific manuscripts that had previously been available only through expensive hand-copied reproductions in monastic libraries.`,
  },
  {
    id: 16,
    topic: "History",
    text: `The Industrial Revolution fundamentally altered economic structures and social relationships throughout Western nations. Factory production replaced traditional craft workshops and created massive urban centers where workers concentrated in dense residential districts surrounding large manufacturing facilities.`,
  },
  {
    id: 17,
    topic: "History",
    text: `Ancient Egyptian civilization flourished along the fertile banks of the Nile River for over three thousand years. Engineers constructed elaborate irrigation systems that channeled seasonal floodwaters into agricultural fields and enabled consistent crop production in an otherwise arid desert environment.`,
  },
  {
    id: 18,
    topic: "History",
    text: `The Silk Road connected distant civilizations across Asia and Europe through an extensive network of trading routes. Merchants transported luxury goods including silk and spices while simultaneously facilitating the exchange of religious ideas and technological innovations between culturally diverse societies.`,
  },
  {
    id: 19,
    topic: "History",
    text: `The Renaissance marked a profound cultural transformation in European intellectual and artistic traditions. Scholars rediscovered classical Greek and Roman philosophical works that inspired new approaches to understanding human nature and challenged established religious interpretations of the natural world.`,
  },

  // ─── 심리학 / 신경과학 (Psychology / Neuroscience) ───
  {
    id: 20,
    topic: "Psychology",
    text: `Neuroscience research has revealed remarkable plasticity in the adult human brain. Experiments demonstrate that neural pathways can reorganize themselves throughout an individual's lifetime in response to learning experiences and environmental stimulation that challenge existing cognitive patterns.`,
  },
  {
    id: 21,
    topic: "Psychology",
    text: `Memory consolidation occurs primarily during specific stages of sleep when the brain processes and organizes information gathered throughout the day. Studies show that individuals who receive adequate rest perform significantly better on tasks requiring recall of recently learned material and complex problem solving.`,
  },
  {
    id: 22,
    topic: "Psychology",
    text: `Language acquisition in children follows remarkably consistent developmental stages regardless of cultural background. Linguists have observed that infants begin by producing universal babbling sounds before gradually narrowing their vocal repertoire to match the specific phonetic patterns heard in their surrounding environment.`,
  },
  {
    id: 23,
    topic: "Psychology",
    text: `Social conformity experiments have demonstrated powerful influences on individual decision making within group settings. Participants frequently abandoned their own accurate judgments and adopted clearly incorrect answers when confronted with unanimous opposing opinions expressed by other members of the experimental group.`,
  },

  // ─── 천문학 / 물리학 (Astronomy / Physics) ───
  {
    id: 24,
    topic: "Astronomy",
    text: `The expanding universe theory fundamentally changed our understanding of cosmic origins and development. Astronomers discovered that distant galaxies are moving away from each other at accelerating velocities which suggests that all matter originated from an incredibly dense singular point approximately fourteen billion years ago.`,
  },
  {
    id: 25,
    topic: "Astronomy",
    text: `Black holes represent some of the most extreme objects predicted by general relativity theory. These regions of spacetime exhibit gravitational forces so powerful that nothing including electromagnetic radiation can escape once it crosses the boundary known as the event horizon surrounding the collapsed stellar core.`,
  },
  {
    id: 26,
    topic: "Astronomy",
    text: `Mars has attracted significant scientific attention as a potential candidate for future human exploration and settlement. Robotic missions have confirmed the presence of frozen water deposits beneath the planetary surface and identified mineral compositions that suggest liquid water once flowed across extensive Martian landscapes.`,
  },

  // ─── 환경과학 (Environmental Science) ───
  {
    id: 27,
    topic: "Environmental Science",
    text: `Deforestation in tropical regions contributes significantly to biodiversity loss and atmospheric carbon accumulation. Conservation organizations advocate for sustainable forestry practices that balance economic development needs with preservation of critical habitat areas that support endangered plant and animal species.`,
  },
  {
    id: 28,
    topic: "Environmental Science",
    text: `Plastic pollution has emerged as a major environmental concern affecting marine ecosystems worldwide. Researchers have documented microscopic plastic fragments in ocean water samples collected from every major body of water and detected these persistent synthetic materials throughout aquatic food chains.`,
  },
  {
    id: 29,
    topic: "Environmental Science",
    text: `Renewable energy technologies have advanced rapidly as alternatives to traditional fossil fuel consumption. Solar panel efficiency has improved dramatically while manufacturing costs have decreased substantially making photovoltaic systems increasingly competitive with conventional electricity generation methods in numerous global markets.`,
  },

  // ─── 사회학 / 경제학 (Sociology / Economics) ───
  {
    id: 30,
    topic: "Sociology",
    text: `Urbanization has transformed demographic patterns across developing nations throughout recent decades. Rural populations have migrated toward metropolitan centers in search of improved employment opportunities and access to educational institutions that provide pathways to higher economic mobility and professional advancement.`,
  },
  {
    id: 31,
    topic: "Economics",
    text: `International trade agreements have reshaped global economic relationships between developing and industrialized nations. Economists debate whether reduced tariff barriers genuinely promote equitable growth or primarily advantage established corporations that possess sufficient resources to exploit expanded market access opportunities.`,
  },
  {
    id: 32,
    topic: "Sociology",
    text: `Digital communication technologies have fundamentally altered patterns of social interaction among younger generations. Researchers observe that online platforms increasingly serve as primary spaces for community formation and identity development replacing traditional physical gathering locations that previously fulfilled these essential social functions.`,
  },

  // ─── 기술 (Technology) ───
  {
    id: 33,
    topic: "Technology",
    text: `Artificial intelligence systems have demonstrated remarkable capabilities in pattern recognition and data analysis tasks. Machine learning algorithms process enormous datasets and identify subtle correlations that human analysts might overlook enabling more accurate predictions in fields ranging from medical diagnosis to financial market forecasting.`,
  },
  {
    id: 34,
    topic: "Technology",
    text: `The development of semiconductor technology enabled the miniaturization of electronic computing devices over several decades. Engineers consistently doubled the number of transistors on integrated circuits approximately every two years following a trend that dramatically increased processing power while reducing manufacturing costs.`,
  },
  {
    id: 35,
    topic: "Technology",
    text: `Quantum computing represents a fundamentally different approach to information processing compared with classical digital systems. These experimental machines exploit quantum mechanical phenomena including superposition and entanglement to perform certain categories of complex calculations exponentially faster than any conventional computer architecture.`,
  },
];
